### ISSUE TITLE
TechFreak

### ISSUE THREAD

**Issue by hamad-SHE** [WDI-HoneyBadger/project-2#29]
TechFreak is a place for everyone who has knowledge about anything with relations to  IT, Programming , design, etc.

ex : anyone who is looking to building a website or application mobile or designing .. in this website you can find many programmers with IT skills ..

**Comment by trevorpreston** [comment]
Thanks!

**Comment by darksys0x** [comment]
https://wireframe.cc/pro/pp/740721f87213107

**Comment by trevorpreston** [comment]
Hey Hamad, 

You need to also have pages where users can add and edit things in your database.  Can you add those to your wireframe?

Then please answer the following required questions for your proposal:
"Your proposal should include:
Name of your app
What your app does
The models you need for your app and any relationships
Wireframes!
A timeline laying out what you're going to do each day. This should specify clear features to be implemented by the end of each day.
A link to the NPM package you intend to use.
Foreseen challenges or obstacles
Technology you intend to use
A link to your repo!"

**Comment by darksys0x** [comment]
i explained you that 
i have 2 model and 2 controller 
i used html js node.js sql , EJS engin maybe use bootstrap ..
today i will complete DB and relation between them ..
tomorrow models , controllers  ..
Wednesday bootstrap 
https://wireframe.cc/pro/pp/740721f87213107

https://github.com/hamad-SHE/project2

**Comment by trevorpreston** [comment]
> i explained you that

I am asking you to put it here so that the other instructors can see it as well.  I've asked all other students to do the same.

> i have 2 model and 2 controller

Remind me - what are your two models?  One for customers and one for personIT, right?

> i used html js node.js sql , EJS engin maybe use bootstrap ..

Why are you using EJS for this?

> today i will complete DB and relation between them ..
> tomorrow models , controllers ..
> Wednesday bootstrap
> https://wireframe.cc/pro/pp/740721f87213107
> 
> https://github.com/hamad-SHE/project2


Last thing - you may want to check your routes.  `/customers` should be a list all customers.
`/ personit/web` should be for all web-developers.  But having `/customers/web` implies that the customers are web developers, is that what you want?

Make these changes and everything is all good 👍

**Comment by darksys0x** [comment]
I am asking you to put it here so that the other instructors can see it as well. I've asked all other students to do the same.

i have 2 model and 2 controller

Remind me - what are your two models? One for customers and one for personIT, right?
yes

i used html js node.js sql , EJS engin maybe use bootstrap ..

Why are you using EJS for this?
i think more easy then mustache  
today i will complete DB and relation between them ..
tomorrow models , controllers ..
Wednesday bootstrap
https://wireframe.cc/pro/pp/740721f87213107

https://github.com/hamad-SHE/project2

Last thing - you may want to check your routes. /customers should be a list all customers.
costumiers have 2 choses  select web or mobile when selected web show all developers of  web and if you want to select any developer you have to full form include information costumer and detail of  project ...
/ personit/web should be for all web-developers. But having /customers/web implies that the customers are web developers, is that what you want?

Make these changes and everything is all good 👍

**Comment by darksys0x** [comment]
![image from ios 3](https://user-images.githubusercontent.com/33722717/50083598-5b380200-0205-11e9-964b-089832772973.jpg)

**Comment by trevorpreston** [comment]
👍
